#---
#- name: Install httpd
#  yum: 
#   name: httpd
#   state: present
---
- name: Install Java 8 using YUM
  yum:
    name: "java-11-openjdk"
    state: present
  become: true
- name: download jenkins.repo
  get_url:
     url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
     dest: /etc/yum.repos.d/jenkins.repo
- name: import jenkins key
  rpm_key:
     state: present
     key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

